version:
	@echo "Current Version of Dotnet:"
	
	@dotnet --version

build:
	@echo "Building..."
	
	@dotnet build

run:
	@echo "Server is on running..."

	@dotnet run

# https-clean-trust
dev-certs:
	@echo "Cleaning..."
	@dotnet dev-certs https --clean
	@dotnet dev-certs https --trust

#docker-run:
#	@docker compose up --build -d

#docker-logs:
#	@docker compose logs -f

#docker-down:
#	@docker compose down

#test:
#	@echo "Testing..."
#	@dotnet test
